# Generated by Django 5.0 on 2024-01-07 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VISApp', '0002_remove_myuser_broj_telefona_myuser_rank_myuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Osoblje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=60)),
                ('prezime', models.CharField(max_length=60)),
                ('datum_rodjenja', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Lokacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('koordinate', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Oprema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('opis', models.CharField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='ITOsoblje',
            fields=[
                ('osoblje_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='VISApp.osoblje')),
                ('sigurnosni_nivo', models.CharField(choices=[('1', 'Nivo1'), ('2', 'Nivo2'), ('3', 'Nivo3')], default='3', max_length=1)),
            ],
            bases=('VISApp.osoblje',),
        ),
        migrations.CreateModel(
            name='VojnoOsoblje',
            fields=[
                ('osoblje_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='VISApp.osoblje')),
                ('rank', models.CharField(blank=True, max_length=30, null=True)),
            ],
            bases=('VISApp.osoblje',),
        ),
        migrations.CreateModel(
            name='Jedinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('baza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='VISApp.baza')),
                ('trenutna_lokacija', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='VISApp.lokacija')),
            ],
        ),
        migrations.AddField(
            model_name='baza',
            name='lokacija',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VISApp.lokacija'),
        ),
        migrations.CreateModel(
            name='Poruka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.CharField(max_length=5000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skladiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('lokacija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VISApp.lokacija')),
            ],
        ),
        migrations.CreateModel(
            name='OpremaSkladiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oprema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VISApp.oprema')),
                ('skladiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VISApp.skladiste')),
            ],
        ),
    ]
