# Generated by Django 5.0 on 2024-01-10 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VISApp', '0003_baza_osoblje_lokacija_oprema_itosoblje_vojnoosoblje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baza',
            name='lokalni_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itosoblje',
            name='korisnicki_profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
