# Generated by Django 5.0 on 2024-01-10 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VISApp', '0004_baza_lokalni_admin_itosoblje_korisnicki_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itosoblje',
            name='korisnicki_profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
