# Generated by Django 5.0 on 2024-01-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VISApp', '0005_alter_itosoblje_korisnicki_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='poruka',
            name='direkcija_poruke',
            field=models.CharField(choices=[('A', 'u_avijaciju'), ('M', 'u_mornaricu'), ('B', 'iz_avijacije'), ('N', 'iz_mornarice')], default='A', max_length=1),
        ),
    ]
