# Generated by Django 5.0 on 2024-01-28 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VISApp', '0006_poruka_direkcija_poruke'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zahtjev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zavrseno', models.BooleanField(default=False)),
                ('lokacija', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='VISApp.lokacija')),
                ('poruka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VISApp.poruka')),
            ],
        ),
    ]
