# Generated by Django 5.0 on 2024-01-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VISApp', '0008_logistika'),
    ]

    operations = [
        migrations.AddField(
            model_name='oprema',
            name='mjerna_jedinica',
            field=models.CharField(default='kg', max_length=50),
        ),
    ]
